sources:
  - name: src
    database: sourcedb
    schema: mk_mall
    tables:
      - name: regions
      - name: nations
      - name: suppliers
        config:
            freshness:
              warn_after: {count: 1, period: day}
              error_after: {count: 3, period: day}
            loaded_at_field: updated_time
      - name: customers
      - name: orders
      - name: lineitems
